package com.crx.mapper;

import com.crx.pojo.Stu;
import com.crx.pojo.StuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    long countByExample(StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    int deleteByExample(StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    int insert(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    int insertSelective(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    List<Stu> selectByExample(StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    Stu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") Stu record, @Param("example") StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    int updateByExample(@Param("record") Stu record, @Param("example") StuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    int updateByPrimaryKeySelective(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbg.generated Thu Jun 20 16:10:53 CST 2019
     */
    int updateByPrimaryKey(Stu record);
}